// generated by stringer -type=kindT; DO NOT EDIT

package io

import "fmt"

const _kindT_name = "tEOFtSymtArrowtLBrackettRBrackettLBracetRBracetEQtCommatColontSemitErr"

var _kindT_index = [...]uint8{0, 4, 8, 14, 23, 32, 39, 46, 49, 55, 61, 66, 70}

func (i kindT) String() string {
	if i < 0 || i >= kindT(len(_kindT_index)-1) {
		return fmt.Sprintf("kindT(%d)", i)
	}
	return _kindT_name[_kindT_index[i]:_kindT_index[i+1]]
}
